# Generated by Django 4.2.2 on 2023-07-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(),
        ),
    ]
