# Generated by Django 4.2.2 on 2023-07-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_auth", "0002_alter_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default=None, max_length=17),
        ),
    ]
