# Generated by Django 4.2.2 on 2023-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_auth", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logintoken",
            name="token",
            field=models.CharField(),
        ),
    ]
